apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
    # kind: backend
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec: 
  replicas: 9
  selector:
    matchLabels:
      app: second-app
      kind: backend
  template: 
    metadata:
      labels:
        app: second-app
        kind: backend
    spec:
      containers:
        - name: second-node
          image: gelo59/kub-first-app:1.1.3
          