ARG NODE_VERSION="14"
FROM node:${NODE_VERSION}
# Default powerline10k theme, no plugins installed
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
    -p docker -p minikube -p kubectl -p 'docker-compose' -p 'zsh-autosuggestions'
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions



